### ISSUE TITLE
Alignment buttons in raptor have no effect

### ISSUE THREAD

**Issue by pilz** [ploneintranet/ploneintranet.prototype#108]
In raptor we have a center and left align button. There is no right align.
Clicking the center button doesn't have any effect though. 
And should we have a right align?

**Comment by ale-rt** [comment]
I was checking this and I can see that the class "cms-center" is correctly set after pressing the relative button.
Indeed we are missing this CSS rule (and others as well):
```css
/* line 6, text-align/style/text-align-front-end.scss
.cms-center {
  text-align: center;
}
```

In my buildout I can find that rule here:
 - src/bower_components/pat-raptor/3rdparty/raptor-front-end.css
